In [4]:
import pandas as pd
import pandera as pa

In [5]:
#Variável valores_ausentes - dados não disponíveis NAN para serem limpos
valores_ausentes = ['**', '###!', '####', '*****', '****', 'NULL']
dados = pd.read_csv('ocorrencia_2010_2020.csv', sep=';', parse_dates=['ocorrencia_dia'], dayfirst=True, na_values=valores_ausentes)
dados.head(10)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211.0,40211.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0.0
1,40349.0,40349.0,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0.0
2,40351.0,40351.0,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0.0
3,39527.0,39527.0,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0.0
4,40324.0,40324.0,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0.0
5,39807.0,39807.0,INCIDENTE,SALVADOR,BA,NaN,2010-01-06,17:53:00,0.0
6,40215.0,40215.0,INCIDENTE,COARI,AM,SBUY,2010-01-07,18:40:00,0.0
7,39707.0,39707.0,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3.0
8,39156.0,39156.0,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2.0
9,39711.0,39711.0,INCIDENTE GRAVE,PARÁ DE MINAS,MG,NaN,2010-01-10,20:00:00,0.0

In [6]:
schema = pa.DataFrameSchema(
    columns = {
        "codigo_ocorrencia":pa.Column(nullable=True),
        #"codigo_ocorrencia2":pa.Column(nullable=True),
        "ocorrencia_classificacao":pa.Column(pa.String, nullable=True),
        "ocorrencia_cidade":pa.Column(pa.String, nullable=True),
        "ocorrencia_uf":pa.Column(pa.String, pa.Check.str_length(2,2), nullable=True),
        "ocorrencia_aerodromo":pa.Column(pa.String, nullable=True),
        "ocorrencia_dia":pa.Column(pa.DateTime, nullable=True),
        "ocorrencia_hora":pa.Column(pa.String, pa.Check.str_matches(r'^([0-1]?[0-9]|[2][0-3]):([0-5][0-9])(:[0-5][0-9])?$'), nullable=True),
        "total_recomendacoes":pa.Column(nullable=True)
    }
)

In [7]:
schema.validate(dados)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211.0,40211.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0.0
1,40349.0,40349.0,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0.0
2,40351.0,40351.0,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0.0
3,39527.0,39527.0,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0.0
4,40324.0,40324.0,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0.0
...,...,...,...,...,...,...,...,...,...
5753,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
5754,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
5755,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
5756,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
5757,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN

In [8]:
dados.head(10)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211.0,40211.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0.0
1,40349.0,40349.0,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0.0
2,40351.0,40351.0,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0.0
3,39527.0,39527.0,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0.0
4,40324.0,40324.0,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0.0
5,39807.0,39807.0,INCIDENTE,SALVADOR,BA,NaN,2010-01-06,17:53:00,0.0
6,40215.0,40215.0,INCIDENTE,COARI,AM,SBUY,2010-01-07,18:40:00,0.0
7,39707.0,39707.0,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3.0
8,39156.0,39156.0,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2.0
9,39711.0,39711.0,INCIDENTE GRAVE,PARÁ DE MINAS,MG,NaN,2010-01-10,20:00:00,0.0

In [9]:
dados.dtypes

codigo_ocorrencia                  float64
codigo_ocorrencia2                 float64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                float64
dtype: object

In [10]:
#Localizar dados pela lable
dados.loc[1]

codigo_ocorrencia                       40349.0
codigo_ocorrencia2                      40349.0
ocorrencia_classificacao              INCIDENTE
ocorrencia_cidade                         BELÉM
ocorrencia_uf                                PA
ocorrencia_aerodromo                       SBBE
ocorrencia_dia              2010-01-03 00:00:00
ocorrencia_hora                        11:05:00
total_recomendacoes                         0.0
Name: 1, dtype: object

In [11]:
#Localizar dados pelo índice
dados.iloc[1]

codigo_ocorrencia                       40349.0
codigo_ocorrencia2                      40349.0
ocorrencia_classificacao              INCIDENTE
ocorrencia_cidade                         BELÉM
ocorrencia_uf                                PA
ocorrencia_aerodromo                       SBBE
ocorrencia_dia              2010-01-03 00:00:00
ocorrencia_hora                        11:05:00
total_recomendacoes                         0.0
Name: 1, dtype: object

In [12]:
dados.iloc[-7]

codigo_ocorrencia                       79844.0
codigo_ocorrencia2                      79844.0
ocorrencia_classificacao              INCIDENTE
ocorrencia_cidade                RIO DE JANEIRO
ocorrencia_uf                                RJ
ocorrencia_aerodromo                       SBJR
ocorrencia_dia              2020-12-31 00:00:00
ocorrencia_hora                        13:24:00
total_recomendacoes                         0.0
Name: 5751, dtype: object

In [13]:
dados.tail()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
5753,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
5754,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
5755,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
5756,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
5757,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN

In [14]:
dados.iloc[10:15]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
10,39789.0,39789.0,INCIDENTE,SÃO PEDRO DO SUL,RS,NaN,2010-01-10,21:30:00,0.0
11,40069.0,40069.0,ACIDENTE,SÃO PAULO,SP,SBMT,2010-01-10,14:50:00,8.0
12,40414.0,40414.0,INCIDENTE,BRASÍLIA,DF,SBBR,2010-01-10,03:00:00,0.0
13,39507.0,39507.0,ACIDENTE,PRIMAVERA DO LESTE,MT,NaN,2010-01-11,17:00:00,2.0
14,40107.0,40107.0,ACIDENTE,GURUPÁ,PA,SNGU,2010-01-12,14:30:00,0.0

In [15]:
dados.loc[:, 'ocorrencia_uf']

0        RJ
1        PA
2        RJ
3        MT
4        RS
       ...
5753    NaN
5754    NaN
5755    NaN
5756    NaN
5757    NaN
Name: ocorrencia_uf, Length: 5758, dtype: object

In [16]:
#Ocorrências cuja classificação == INCIDENTE GRAVE
filtro = dados.ocorrencia_classificacao == 'INCIDENTE GRAVE'
dados.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707.0,39707.0,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3.0
8,39156.0,39156.0,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2.0
9,39711.0,39711.0,INCIDENTE GRAVE,PARÁ DE MINAS,MG,NaN,2010-01-10,20:00:00,0.0
29,39709.0,39709.0,INCIDENTE GRAVE,CURITIBA,PR,SBBI,2010-01-23,16:36:00,2.0
35,39487.0,39487.0,INCIDENTE GRAVE,PALMAS,TO,SBPJ,2010-01-26,16:50:00,0.0
...,...,...,...,...,...,...,...,...,...
5741,79754.0,79754.0,INCIDENTE GRAVE,NOVA MARINGÁ,MT,NaN,2020-12-28,13:00:00,0.0
5744,79753.0,79753.0,INCIDENTE GRAVE,GOIATUBA,GO,NaN,2020-12-29,12:00:00,0.0
5746,79769.0,79769.0,INCIDENTE GRAVE,MANOEL URBANO,AC,SIMB,2020-12-29,18:30:00,0.0
5748,79757.0,79757.0,INCIDENTE GRAVE,LAGOA DA CONFUSÃO,TO,NaN,2020-12-30,18:30:00,0.0
5750,79756.0,79756.0,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,09:00:00,0.0

In [17]:
#Ocorrências cuja classificação == INCIDENTE GRAVE e o estado == SP
filtro = dados.ocorrencia_classificacao == 'INCIDENTE GRAVE'
filtro2 = dados.ocorrencia_uf == 'SP'
dados.loc[filtro & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
136,40270.0,40270.0,INCIDENTE GRAVE,PIRASSUNUNGA,SP,SDPY,2010-04-15,20:15:00,0.0
171,40620.0,40620.0,INCIDENTE GRAVE,GUARULHOS,SP,SBGR,2010-05-06,15:50:00,0.0
219,41411.0,41411.0,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2010-06-08,19:30:00,2.0
297,42289.0,42289.0,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2010-07-29,20:06:00,0.0
314,42323.0,42323.0,INCIDENTE GRAVE,SÃO JOSÉ DO RIO PRETO,SP,SBSR,2010-08-05,12:01:00,0.0
...,...,...,...,...,...,...,...,...,...
5591,79540.0,79540.0,INCIDENTE GRAVE,SÃO PAULO,SP,NaN,2020-09-12,13:10:00,0.0
5610,79566.0,79566.0,INCIDENTE GRAVE,REGENTE FEIJÓ,SP,SDYJ,2020-09-27,19:33:00,0.0
5704,79739.0,79739.0,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2020-12-03,14:42:00,0.0
5705,79705.0,79705.0,INCIDENTE GRAVE,SOROCABA,SP,SDCO,2020-12-04,15:30:00,0.0
5715,79718.0,79718.0,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2020-12-11,13:50:00,0.0

In [18]:
#Ocorrências cuja classificação == INCIDENTE GRAVE ou estado == SP
filtro = dados.ocorrencia_classificacao == 'INCIDENTE GRAVE'
filtro2 = dados.ocorrencia_uf == 'SP'
dados.loc[filtro | filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707.0,39707.0,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3.0
8,39156.0,39156.0,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2.0
9,39711.0,39711.0,INCIDENTE GRAVE,PARÁ DE MINAS,MG,NaN,2010-01-10,20:00:00,0.0
11,40069.0,40069.0,ACIDENTE,SÃO PAULO,SP,SBMT,2010-01-10,14:50:00,8.0
16,39809.0,39809.0,INCIDENTE,SÃO PAULO,SP,NaN,2010-01-15,15:00:00,0.0
...,...,...,...,...,...,...,...,...,...
5744,79753.0,79753.0,INCIDENTE GRAVE,GOIATUBA,GO,NaN,2020-12-29,12:00:00,0.0
5746,79769.0,79769.0,INCIDENTE GRAVE,MANOEL URBANO,AC,SIMB,2020-12-29,18:30:00,0.0
5747,79804.0,79804.0,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0.0
5748,79757.0,79757.0,INCIDENTE GRAVE,LAGOA DA CONFUSÃO,TO,NaN,2020-12-30,18:30:00,0.0
5750,79756.0,79756.0,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,09:00:00,0.0

In [19]:
#Ocorrências cuja classificação == INCIDENTE GRAVE ou INCIDENTE e o estado == SP
filtro = (dados.ocorrencia_classificacao == 'INCIDENTE GRAVE') | (dados.ocorrencia_classificacao == 'INCIDENTE')
filtro2 = dados.ocorrencia_uf == 'SP'
dados.loc[filtro & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
16,39809.0,39809.0,INCIDENTE,SÃO PAULO,SP,NaN,2010-01-15,15:00:00,0.0
18,39828.0,39828.0,INCIDENTE,SANTOS,SP,NaN,2010-01-15,17:45:00,0.0
26,39847.0,39847.0,INCIDENTE,SOROCABA,SP,NaN,2010-01-20,13:10:00,0.0
27,39768.0,39768.0,INCIDENTE,CAMPINAS,SP,NaN,2010-01-21,20:45:00,0.0
33,39848.0,39848.0,INCIDENTE,GUARULHOS,SP,SBGR,2010-01-25,17:05:00,0.0
...,...,...,...,...,...,...,...,...,...
5704,79739.0,79739.0,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2020-12-03,14:42:00,0.0
5705,79705.0,79705.0,INCIDENTE GRAVE,SOROCABA,SP,SDCO,2020-12-04,15:30:00,0.0
5715,79718.0,79718.0,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2020-12-11,13:50:00,0.0
5742,79800.0,79800.0,INCIDENTE,SÃO PAULO,SP,SBMT,2020-12-28,10:15:00,0.0
5747,79804.0,79804.0,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0.0

In [20]:
#Ocorrências cuja classificação == INCIDENTE GRAVE ou INCIDENTE e o estado == SP com o método isin
filtro = dados.ocorrencia_classificacao.isin(['INCIDENTE GRAVE', 'INCIDENTE'])
filtro2 = dados.ocorrencia_uf == 'SP'
dados.loc[filtro & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
16,39809.0,39809.0,INCIDENTE,SÃO PAULO,SP,NaN,2010-01-15,15:00:00,0.0
18,39828.0,39828.0,INCIDENTE,SANTOS,SP,NaN,2010-01-15,17:45:00,0.0
26,39847.0,39847.0,INCIDENTE,SOROCABA,SP,NaN,2010-01-20,13:10:00,0.0
27,39768.0,39768.0,INCIDENTE,CAMPINAS,SP,NaN,2010-01-21,20:45:00,0.0
33,39848.0,39848.0,INCIDENTE,GUARULHOS,SP,SBGR,2010-01-25,17:05:00,0.0
...,...,...,...,...,...,...,...,...,...
5704,79739.0,79739.0,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2020-12-03,14:42:00,0.0
5705,79705.0,79705.0,INCIDENTE GRAVE,SOROCABA,SP,SDCO,2020-12-04,15:30:00,0.0
5715,79718.0,79718.0,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2020-12-11,13:50:00,0.0
5742,79800.0,79800.0,INCIDENTE,SÃO PAULO,SP,SBMT,2020-12-28,10:15:00,0.0
5747,79804.0,79804.0,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0.0

In [21]:
#Ocorrências cuja cidades começam com a letra C
filtro = dados.ocorrencia_cidade.str[0] == 'C'
dados.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
6,40215.0,40215.0,INCIDENTE,COARI,AM,SBUY,2010-01-07,18:40:00,0.0
7,39707.0,39707.0,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3.0
8,39156.0,39156.0,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2.0
15,39315.0,39315.0,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0.0
20,40310.0,40310.0,INCIDENTE,CRUZEIRO DO SUL,AC,SBCZ,2010-01-18,19:32:00,0.0
...,...,...,...,...,...,...,...,...,...
5661,79649.0,79649.0,INCIDENTE,CAMPINAS,SP,SBKP,2020-11-04,22:39:00,0.0
5663,79652.0,79652.0,INCIDENTE,CONFINS,MG,SBCF,2020-11-06,14:20:00,0.0
5680,79683.0,79683.0,INCIDENTE,CRUZEIRO DO SUL,AC,SBCZ,2020-11-16,22:00:00,0.0
5696,79692.0,79692.0,ACIDENTE,CATANDUVA,SP,SDCD,2020-11-28,12:50:00,0.0
5747,79804.0,79804.0,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0.0

In [22]:
#Ocorrências cuja cidades terminam com os caracteres MA
filtro = dados.ocorrencia_cidade.str[-2:] == 'MA'
dados.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707.0,39707.0,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3.0
15,39315.0,39315.0,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0.0
408,43062.0,43062.0,ACIDENTE,NOVO GAMA,GO,NaN,2010-09-25,16:30:00,1.0
688,44198.0,44198.0,ACIDENTE,BURITAMA,SP,NaN,2011-03-19,11:18:00,0.0
1035,51785.0,51785.0,INCIDENTE,BURITAMA,SP,SIBX,2011-10-25,19:15:00,0.0
1377,45939.0,45939.0,ACIDENTE,UMUARAMA,PR,NaN,2012-05-30,19:00:00,0.0
1401,46180.0,46180.0,ACIDENTE,AURIFLAMA,SP,NaN,2012-06-16,19:30:00,0.0
2099,49113.0,49113.0,INCIDENTE GRAVE,NOVA LIMA,MG,NaN,2013-06-15,12:00:00,4.0
2102,48799.0,48799.0,ACIDENTE,CANUTAMA,AM,NaN,2013-06-18,21:30:00,0.0
2655,51347.0,51347.0,INCIDENTE,DIADEMA,SP,NaN,2014-05-04,16:00:00,0.0
2855,52340.0,52340.0,ACIDENTE,FAMA,MG,NaN,2014-09-20,15:00:00,1.0
2966,52832.0,52832.0,ACIDENTE,BURITAMA,SP,NaN,2014-12-14,23:40:00,0.0
2997,52979.0,52979.0,ACIDENTE,IVINHEMA,MS,NaN,2015-01-02,14:50:00,0.0
3040,52984.0,52984.0,ACIDENTE,NOVA LIMA,MG,SJLY,2015-02-01,15:10:00,0.0
3092,53596.0,53596.0,INCIDENTE,ITAPEMA,SC,NaN,2015-03-10,21:35:00,0.0
3157,53223.0,53223.0,ACIDENTE,PINDORAMA,SP,NaN,2015-04-22,12:45:00,0.0
3171,53265.0,53265.0,ACIDENTE,PACARAIMA,RR,SDMM,2015-05-05,16:05:00,2.0
3189,53271.0,53271.0,INCIDENTE GRAVE,UMUARAMA,PR,NaN,2015-05-17,17:00:00,0.0
3682,65414.0,65414.0,INCIDENTE GRAVE,NOVA LIMA,MG,SJLY,2016-07-08,19:50:00,1.0
3725,65633.0,65633.0,INCIDENTE GRAVE,NOVA LIMA,MG,NaN,2016-08-31,17:40:00,0.0
3881,66265.0,66265.0,ACIDENTE,BURITAMA,SP,NaN,2017-01-13,16:00:00,0.0
4229,77371.0,77371.0,ACIDENTE,CANUTAMA,AM,SDKH,2017-11-02,19:30:00,1.0
4311,77612.0,77612.0,ACIDENTE,ITAPEMA,SC,NaN,2018-01-06,10:30:00,0.0
4574,78080.0,78080.0,ACIDENTE,ITAPEMA,SC,NaN,2018-07-28,14:20:00,0.0
4986,78867.0,78867.0,INCIDENTE,IRACEMA,RR,NaN,2019-07-06,00:00:00,0.0
5070,78923.0,78923.0,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2019-09-03,14:00:00,0.0
5080,78782.0,78782.0,ACIDENTE,IVINHEMA,MS,NaN,2019-09-08,17:45:00,0.0
5405,79282.0,79282.0,ACIDENTE,ITURAMA,MG,NaN,2020-04-11,12:20:00,0.0
5440,79338.0,79338.0,INCIDENTE,IVINHEMA,MS,NaN,2020-05-15,09:40:00,0.0
5474,79400.0,79400.0,INCIDENTE,IBIRAMA,SC,NaN,2020-06-09,14:00:00,0.0

In [23]:
#Ocorrências cuja cidades contém(em qualquer parte da string) os caracteres MA
filtro = dados.ocorrencia_cidade.str.contains('MA')
dados.loc[filtro]

ValueError: Cannot mask with non-boolean array containing NA / NaN values

In [ ]:
#Obter ocorrencia_dia do ano de 2015
filtro = dados.ocorrencia_dia.dt.year == 2015
dados.loc[filtro]

In [24]:
#Obter ocorrencia_dia do ano de 2015 e mês 12
filtro = (dados.ocorrencia_dia.dt.year == 2015) & (dados.ocorrencia_dia.dt.month == 12)
dados.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
3428,53573.0,53573.0,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-01,02:48:00,0.0
3429,60601.0,60601.0,INCIDENTE,PALMAS,TO,SBPJ,2015-12-01,16:05:00,0.0
3430,53634.0,53634.0,INCIDENTE,PALMAS,TO,SBPJ,2015-12-02,17:45:00,0.0
3431,53636.0,53636.0,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-12-02,17:42:00,0.0
3432,53575.0,53575.0,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0.0
3433,60637.0,60637.0,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0.0
3434,53625.0,53625.0,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3.0
3435,53626.0,53626.0,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1.0
3436,53628.0,53628.0,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1.0
3437,53629.0,53629.0,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0.0
3438,53631.0,53631.0,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0.0
3439,60636.0,60636.0,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0.0
3440,53627.0,53627.0,INCIDENTE,TERESINA,PI,SBTE,2015-12-12,19:05:00,0.0
3441,60604.0,60604.0,INCIDENTE,GOIÂNIA,GO,SBGO,2015-12-12,14:34:00,0.0
3442,60611.0,60611.0,INCIDENTE,SÃO PAULO,SP,SBSP,2015-12-12,15:30:00,0.0
3443,60613.0,60613.0,ACIDENTE,JUSCIMEIRA,MT,SWMO,2015-12-12,08:31:00,0.0
3444,60629.0,60629.0,ACIDENTE,RIO GRANDE,RS,NaN,2015-12-12,10:40:00,0.0
3445,53630.0,53630.0,INCIDENTE,MARÍLIA,SP,SBML,2015-12-13,13:50:00,0.0
3446,60603.0,60603.0,INCIDENTE,LONDRINA,PR,SBLO,2015-12-13,17:46:00,0.0
3447,60612.0,60612.0,ACIDENTE,BENTO GONÇALVES,RS,SSBG,2015-12-13,20:30:00,0.0
3448,60783.0,60783.0,ACIDENTE,LAGES,SC,NaN,2015-12-13,14:00:00,3.0
3449,53639.0,53639.0,INCIDENTE,LOUVEIRA,SP,SDAM,2015-12-15,14:20:00,0.0
3450,60609.0,60609.0,INCIDENTE GRAVE,ARAGUAÍNA,TO,SWGN,2015-12-15,13:00:00,0.0
3451,60616.0,60616.0,ACIDENTE,PALOTINA,PR,NaN,2015-12-15,20:30:00,0.0
3452,60620.0,60620.0,ACIDENTE,RIO DE JANEIRO,RJ,SBJR,2015-12-15,16:50:00,4.0
3453,60645.0,60645.0,ACIDENTE,SERTÃOZINHO,SP,NaN,2015-12-15,13:00:00,0.0
3454,60608.0,60608.0,INCIDENTE,BELO HORIZONTE,MG,SBPR,2015-12-16,10:38:00,0.0
3455,60625.0,60625.0,ACIDENTE,ITÁPOLIS,SP,SDIO,2015-12-17,21:30:00,1.0
3456,60605.0,60605.0,INCIDENTE,UBERLÂNDIA,MG,SBUL,2015-12-18,10:25:00,0.0
3457,60610.0,60610.0,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-12-18,18:45:00,0.0
3458,60602.0,60602.0,INCIDENTE,RIBEIRÃO PRETO,SP,SBRP,2015-12-22,06:27:00,0.0
3459,60615.0,60615.0,INCIDENTE,SÃO PAULO,SP,SBMT,2015-12-22,13:07:00,0.0
3460,60640.0,60640.0,INCIDENTE,CASCAVEL,PR,SBCA,2015-12-23,13:20:00,0.0
3461,60641.0,60641.0,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-23,15:53:00,0.0
3462,60632.0,60632.0,INCIDENTE GRAVE,ITABERÁ,SP,NaN,2015-12-24,14:00:00,0.0
3463,60600.0,60600.0,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-25,19:00:00,0.0
3464,60642.0,60642.0,INCIDENTE,SÃO FRANCISCO DO SUL,SC,SSSS,2015-12-26,16:00:00,0.0
3465,60631.0,60631.0,ACIDENTE,MAÇAMBARÁ,RS,NaN,2015-12-28,19:00:00,2.0
3466,60649.0,60649.0,ACIDENTE,PORTO BELO,SC,SDEN,2015-12-31,14:00:00,0.0

In [25]:
#Obter ocorrencia_dia do ano de 2015 e mês 12
filtro_ano_mes = (dados.ocorrencia_dia.dt.year == 2015) & (dados.ocorrencia_dia.dt.month == 12)
filtro_dia = dados.ocorrencia_dia.dt.day == 8
dados.loc[filtro & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
3428,53573.0,53573.0,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-01,02:48:00,0.0
3431,53636.0,53636.0,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-12-02,17:42:00,0.0
3435,53626.0,53626.0,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1.0
3436,53628.0,53628.0,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1.0
3437,53629.0,53629.0,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0.0
3438,53631.0,53631.0,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0.0
3442,60611.0,60611.0,INCIDENTE,SÃO PAULO,SP,SBSP,2015-12-12,15:30:00,0.0
3445,53630.0,53630.0,INCIDENTE,MARÍLIA,SP,SBML,2015-12-13,13:50:00,0.0
3449,53639.0,53639.0,INCIDENTE,LOUVEIRA,SP,SDAM,2015-12-15,14:20:00,0.0
3453,60645.0,60645.0,ACIDENTE,SERTÃOZINHO,SP,NaN,2015-12-15,13:00:00,0.0
3455,60625.0,60625.0,ACIDENTE,ITÁPOLIS,SP,SDIO,2015-12-17,21:30:00,1.0
3457,60610.0,60610.0,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-12-18,18:45:00,0.0
3458,60602.0,60602.0,INCIDENTE,RIBEIRÃO PRETO,SP,SBRP,2015-12-22,06:27:00,0.0
3459,60615.0,60615.0,INCIDENTE,SÃO PAULO,SP,SBMT,2015-12-22,13:07:00,0.0
3462,60632.0,60632.0,INCIDENTE GRAVE,ITABERÁ,SP,NaN,2015-12-24,14:00:00,0.0
3463,60600.0,60600.0,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-25,19:00:00,0.0

In [26]:
#Obter ocorrencia_dia do ano de 2015 e mês 12
filtro_ano_mes = (dados.ocorrencia_dia.dt.year == 2015) & (dados.ocorrencia_dia.dt.month == 12)
filtro_dia_inicio = (dados.ocorrencia_dia.dt.day >= 3)
filtro_dia_fim = (dados.ocorrencia_dia.dt.day <=8)
dados.loc[filtro_ano_mes & filtro_dia_inicio & filtro_dia_fim]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
3432,53575.0,53575.0,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0.0
3433,60637.0,60637.0,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0.0
3434,53625.0,53625.0,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3.0
3435,53626.0,53626.0,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1.0
3436,53628.0,53628.0,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1.0
3437,53629.0,53629.0,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0.0
3438,53631.0,53631.0,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0.0
3439,60636.0,60636.0,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0.0

In [27]:
dados['ocorrencia_dia_hora'] = pd.to_datetime(dados.ocorrencia_dia.astype(str) + ' ' + dados.ocorrencia_hora)
dados.head()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
0,40211.0,40211.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0.0,2010-01-03 12:00:00
1,40349.0,40349.0,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0.0,2010-01-03 11:05:00
2,40351.0,40351.0,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0.0,2010-01-03 03:00:00
3,39527.0,39527.0,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0.0,2010-01-04 17:30:00
4,40324.0,40324.0,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0.0,2010-01-05 19:25:00

In [28]:
dados.dtypes

codigo_ocorrencia                  float64
codigo_ocorrencia2                 float64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                float64
ocorrencia_dia_hora         datetime64[ns]
dtype: object

In [29]:
filtro_ano_mes = (dados.ocorrencia_dia.dt.year == 2015) & (dados.ocorrencia_dia.dt.month == 12)
filtro_dia_inicio = (dados.ocorrencia_dia.dt.day >= 3)
filtro_dia_fim = (dados.ocorrencia_dia_hora.dt.day <=8)
dados.loc[filtro_ano_mes & filtro_dia_inicio & filtro_dia_fim]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
3432,53575.0,53575.0,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0.0,2015-12-03 10:50:00
3433,60637.0,60637.0,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0.0,2015-12-03 16:47:00
3434,53625.0,53625.0,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3.0,2015-12-06 13:10:00
3435,53626.0,53626.0,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1.0,2015-12-06 15:00:00
3436,53628.0,53628.0,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1.0,2015-12-08 14:30:00
3437,53629.0,53629.0,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0.0,2015-12-08 10:20:00
3438,53631.0,53631.0,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0.0,2015-12-08 16:19:00
3439,60636.0,60636.0,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0.0,2015-12-08 13:00:00

In [30]:
filtro1 = (dados.ocorrencia_dia_hora >= '2015-12-03 11:00:00') & (dados.ocorrencia_dia_hora <= '2015-12-08 13:00:00')
dados.loc[filtro1]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
3433,60637.0,60637.0,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0.0,2015-12-03 16:47:00
3434,53625.0,53625.0,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3.0,2015-12-06 13:10:00
3435,53626.0,53626.0,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1.0,2015-12-06 15:00:00
3437,53629.0,53629.0,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0.0,2015-12-08 10:20:00
3439,60636.0,60636.0,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0.0,2015-12-08 13:00:00

In [31]:
#Ocorrências do ano de 2015 e mês 03
filtro = dados.ocorrencia_dia.dt.year == 2015
filtro2 = dados.ocorrencia_dia.dt.month == 3
dados_2015_3 = dados.loc[filtro & filtro2]
dados_2015_3

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
3086,53183.0,53183.0,ACIDENTE,AMAPORÃ,PR,NaN,2015-03-02,23:00:00,0.0,2015-03-02 23:00:00
3087,53120.0,53120.0,ACIDENTE,CHAVES,PA,SNXW,2015-03-04,13:30:00,0.0,2015-03-04 13:30:00
3088,53109.0,53109.0,ACIDENTE,CAMPO GRANDE,MS,SSIE,2015-03-05,13:50:00,0.0,2015-03-05 13:50:00
3089,53112.0,53112.0,ACIDENTE,MOGI GUAÇU,SP,NaN,2015-03-06,21:00:00,0.0,2015-03-06 21:00:00
3090,53152.0,53152.0,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,SBRJ,2015-03-10,11:30:00,2.0,2015-03-10 11:30:00
3091,53167.0,53167.0,INCIDENTE,MARABÁ,PA,SBMA,2015-03-10,17:33:00,0.0,2015-03-10 17:33:00
3092,53596.0,53596.0,INCIDENTE,ITAPEMA,SC,NaN,2015-03-10,21:35:00,0.0,2015-03-10 21:35:00
3093,53149.0,53149.0,ACIDENTE,TABATINGA,AM,SBTT,2015-03-11,23:25:00,0.0,2015-03-11 23:25:00
3094,53148.0,53148.0,ACIDENTE,ARARAS,SP,SDEH,2015-03-12,12:40:00,0.0,2015-03-12 12:40:00
3095,53153.0,53153.0,INCIDENTE,PORTO ALEGRE,RS,SBPA,2015-03-13,15:45:00,0.0,2015-03-13 15:45:00
3096,53154.0,53154.0,INCIDENTE,SOROCABA,SP,SDCO,2015-03-13,14:40:00,0.0,2015-03-13 14:40:00
3097,53238.0,53238.0,INCIDENTE,SERRA,ES,NaN,2015-03-13,11:30:00,0.0,2015-03-13 11:30:00
3098,53189.0,53189.0,INCIDENTE,CONFINS,MG,SBCF,2015-03-14,07:20:00,0.0,2015-03-14 07:20:00
3099,53193.0,53193.0,ACIDENTE,CANARANA,MT,NaN,2015-03-14,18:00:00,0.0,2015-03-14 18:00:00
3100,53164.0,53164.0,ACIDENTE,PRINCESA ISABEL,PB,NaN,2015-03-15,18:30:00,0.0,2015-03-15 18:30:00
3101,53151.0,53151.0,INCIDENTE GRAVE,MAUÉS,AM,SWMW,2015-03-16,18:07:00,1.0,2015-03-16 18:07:00
3102,53168.0,53168.0,INCIDENTE,PARÁ DE MINAS,MG,SNPA,2015-03-16,21:05:00,0.0,2015-03-16 21:05:00
3103,53169.0,53169.0,INCIDENTE,BELÉM,PA,SBBE,2015-03-19,03:25:00,0.0,2015-03-19 03:25:00
3104,53165.0,53165.0,INCIDENTE GRAVE,SÃO DESIDÉRIO,BA,NaN,2015-03-20,14:35:00,0.0,2015-03-20 14:35:00
3105,53188.0,53188.0,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2015-03-20,21:00:00,0.0,2015-03-20 21:00:00
3106,53184.0,53184.0,ACIDENTE,PORTO UNIÃO,SC,NaN,2015-03-22,13:44:00,0.0,2015-03-22 13:44:00
3107,53178.0,53178.0,ACIDENTE,DIAMANTINO,MT,NaN,2015-03-23,17:15:00,0.0,2015-03-23 17:15:00
3108,53182.0,53182.0,ACIDENTE,SANTA LUZIA,MA,NaN,2015-03-23,20:40:00,0.0,2015-03-23 20:40:00
3109,53166.0,53166.0,INCIDENTE GRAVE,RIACHÃO DAS NEVES,BA,NaN,2015-03-24,14:45:00,0.0,2015-03-24 14:45:00
3110,53170.0,53170.0,INCIDENTE,CONFINS,MG,SBCF,2015-03-24,17:57:00,0.0,2015-03-24 17:57:00
3111,53185.0,53185.0,INCIDENTE,CURITIBA,PR,SBCT,2015-03-24,23:01:00,0.0,2015-03-24 23:01:00
3112,53412.0,53412.0,INCIDENTE GRAVE,MACAÉ,RJ,NaN,2015-03-24,16:35:00,0.0,2015-03-24 16:35:00
3113,53194.0,53194.0,ACIDENTE,GUARACIABA DO NORTE,CE,SWBE,2015-03-26,20:30:00,0.0,2015-03-26 20:30:00
3114,53186.0,53186.0,INCIDENTE,BRASÍLIA,DF,NaN,2015-03-27,14:55:00,0.0,2015-03-27 14:55:00
3115,53179.0,53179.0,ACIDENTE,CAIAPÔNIA,GO,NaN,2015-03-28,10:30:00,0.0,2015-03-28 10:30:00
3116,53180.0,53180.0,ACIDENTE,ARAGUARI,MG,NaN,2015-03-28,18:52:00,0.0,2015-03-28 18:52:00
3117,53190.0,53190.0,INCIDENTE,CAMPINAS,SP,SBKP,2015-03-28,16:26:00,0.0,2015-03-28 16:26:00
3118,53212.0,53212.0,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-03-28,17:32:00,0.0,2015-03-28 17:32:00
3119,53213.0,53213.0,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-03-28,15:51:00,0.0,2015-03-28 15:51:00
3120,53181.0,53181.0,ACIDENTE,COLÍDER,MT,NaN,2015-03-29,20:17:00,0.0,2015-03-29 20:17:00
3121,53187.0,53187.0,INCIDENTE,JOINVILLE,SC,SBJV,2015-03-29,18:36:00,0.0,2015-03-29 18:36:00
3122,53211.0,53211.0,INCIDENTE,BAURU,SP,SBBU,2015-03-30,19:40:00,0.0,2015-03-30 19:40:00

In [32]:
dados_2015_3.count()

codigo_ocorrencia           37
codigo_ocorrencia2          37
ocorrencia_classificacao    37
ocorrencia_cidade           37
ocorrencia_uf               37
ocorrencia_aerodromo        21
ocorrencia_dia              37
ocorrencia_hora             37
total_recomendacoes         37
ocorrencia_dia_hora         37
dtype: int64

In [33]:
#Agrupamento e count por codigo_ocorrencia 
dados_2015_3.groupby(['ocorrencia_classificacao']).codigo_ocorrencia.count()

ocorrencia_classificacao
ACIDENTE           15
INCIDENTE          17
INCIDENTE GRAVE     5
Name: codigo_ocorrencia, dtype: int64

In [34]:
dados_2015_3.groupby(['ocorrencia_classificacao']).ocorrencia_aerodromo.count()

ocorrencia_classificacao
ACIDENTE            5
INCIDENTE          14
INCIDENTE GRAVE     2
Name: ocorrencia_aerodromo, dtype: int64

In [35]:
# Size ele verifica o tamanho dos registros que foram agrupados por ordem crescente 
dados_2015_3.groupby(['ocorrencia_classificacao']).ocorrencia_aerodromo.size().sort_values(ascending=False)

ocorrencia_classificacao
INCIDENTE          17
ACIDENTE           15
INCIDENTE GRAVE     5
Name: ocorrencia_aerodromo, dtype: int64

In [39]:
filtro = dados.ocorrencia_dia.dt.year == 2010
filtro2 = dados.ocorrencia_uf.isin(['SP', 'MG', 'ES', 'RJ'])
dados_2010 = dados.loc[filtro & filtro2]
dados_2010

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
0,40211.0,40211.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0.0,2010-01-03 12:00:00
2,40351.0,40351.0,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0.0,2010-01-03 03:00:00
9,39711.0,39711.0,INCIDENTE GRAVE,PARÁ DE MINAS,MG,NaN,2010-01-10,20:00:00,0.0,2010-01-10 20:00:00
11,40069.0,40069.0,ACIDENTE,SÃO PAULO,SP,SBMT,2010-01-10,14:50:00,8.0,2010-01-10 14:50:00
16,39809.0,39809.0,INCIDENTE,SÃO PAULO,SP,NaN,2010-01-15,15:00:00,0.0,2010-01-15 15:00:00
...,...,...,...,...,...,...,...,...,...,...
541,43722.0,43722.0,ACIDENTE,CAJOBI,SP,NaN,2010-12-23,11:00:00,0.0,2010-12-23 11:00:00
544,43548.0,43548.0,INCIDENTE,SÃO PAULO,SP,SBSP,2010-12-26,22:10:00,0.0,2010-12-26 22:10:00
548,43724.0,43724.0,ACIDENTE,COSMÓPOLIS,SP,NaN,2010-12-29,12:00:00,0.0,2010-12-29 12:00:00
550,43730.0,43730.0,INCIDENTE,VITÓRIA,ES,NaN,2010-12-30,18:10:00,0.0,2010-12-30 18:10:00
551,43975.0,43975.0,INCIDENTE,ARRAIAL DO CABO,RJ,NaN,2010-12-30,14:28:00,0.0,2010-12-30 14:28:00

In [49]:
# Agrupamento por ocorrências na região sudeeste
dados_2010.groupby(['ocorrencia_classificacao']).size()

ocorrencia_classificacao
ACIDENTE            40
INCIDENTE          170
INCIDENTE GRAVE     18
dtype: int64

In [47]:
dados_2010.count()

codigo_ocorrencia           228
codigo_ocorrencia2          228
ocorrencia_classificacao    228
ocorrencia_cidade           228
ocorrencia_uf               228
ocorrencia_aerodromo        127
ocorrencia_dia              228
ocorrencia_hora             228
total_recomendacoes         228
ocorrencia_dia_hora         228
dtype: int64

In [51]:
dados_2010.groupby(['ocorrencia_uf', 'ocorrencia_classificacao']).size()

ocorrencia_uf  ocorrencia_classificacao
ES             INCIDENTE                    5
MG             ACIDENTE                     7
               INCIDENTE                   39
               INCIDENTE GRAVE              5
RJ             ACIDENTE                     9
               INCIDENTE                   52
               INCIDENTE GRAVE              4
SP             ACIDENTE                    24
               INCIDENTE                   74
               INCIDENTE GRAVE              9
dtype: int64

In [54]:
dados_2010.groupby(['ocorrencia_cidade']).size().sort_values(ascending=False)

ocorrencia_cidade
RIO DE JANEIRO           47
SÃO PAULO                33
GUARULHOS                18
BELO HORIZONTE           17
CAMPINAS                 13
MACAÉ                    12
CONFINS                   7
UBERLÂNDIA                5
JUIZ DE FORA              4
VITÓRIA                   4
MARÍLIA                   3
SÃO JOSÉ DOS CAMPOS       3
SÃO JOSÉ DO RIO PRETO     3
SOROCABA                  2
ITANHAÉM                  2
RIBEIRÃO PRETO            2
IPATINGA                  2
POÇOS DE CALDAS           2
DIVINÓPOLIS               2
BAURU                     2
JUNDIAÍ                   2
ARARAQUARA                2
CAMPOS DOS GOYTACAZES     2
AREALVA                   2
MONTES CLAROS             2
UBERABA                   2
POUSO ALEGRE              1
PIRACICABA                1
PIRASSUNUNGA              1
ARRAIAL DO CABO           1
RESENDE                   1
PENÁPOLIS                 1
SANTOS                    1
SERRA NEGRA               1
SÃO BERNARDO DO CAMPO     1
TIMÓTEO                   1
ARAÇATUBA                 1
PIACATU                   1
BOM JESUS DO AMPARO       1
PARÁ DE MINAS             1
OLÍMPIA                   1
BRAGANÇA PAULISTA         1
BROTAS                    1
CAJOBI                    1
CAMANDUCAIA               1
BOITUVA                   1
CASIMIRO DE ABREU         1
BOCAINA                   1
COROMANDEL                1
COSMÓPOLIS                1
DIAMANTINA                1
BEBEDOURO                 1
IPERÓ                     1
ITÁPOLIS                  1
LINHARES                  1
MANGARATIBA               1
BOM JESUS DO GALHO        1
NOVO HORIZONTE            1
AMERICANA                 1
dtype: int64

In [55]:
filtro = dados_2010.ocorrencia_cidade == 'RIO DE JANEIRO'
dados_2010.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
0,40211.0,40211.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0.0,2010-01-03 12:00:00
2,40351.0,40351.0,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0.0,2010-01-03 03:00:00
19,44575.0,44575.0,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-01-17,12:27:00,0.0,2010-01-17 12:27:00
23,40311.0,40311.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-19,13:20:00,0.0,2010-01-19 13:20:00
24,41577.0,41577.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-19,12:16:00,0.0,2010-01-19 12:16:00
30,39849.0,39849.0,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-01-23,03:30:00,0.0,2010-01-23 03:30:00
39,40617.0,40617.0,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-01-27,20:06:00,0.0,2010-01-27 20:06:00
49,39295.0,39295.0,ACIDENTE,RIO DE JANEIRO,RJ,NaN,2010-02-06,21:09:00,0.0,2010-02-06 21:09:00
71,39987.0,39987.0,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-02-24,19:37:00,0.0,2010-02-24 19:37:00
101,40210.0,40210.0,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-03-20,20:02:00,0.0,2010-03-20 20:02:00
105,40209.0,40209.0,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-03-21,13:46:00,0.0,2010-03-21 13:46:00
107,40330.0,40330.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-03-24,11:35:00,0.0,2010-03-24 11:35:00
119,40190.0,40190.0,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-04-06,02:35:00,3.0,2010-04-06 02:35:00
139,40294.0,40294.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-04-16,20:00:00,0.0,2010-04-16 20:00:00
144,40293.0,40293.0,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-04-18,16:23:00,0.0,2010-04-18 16:23:00
154,40581.0,40581.0,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-04-21,13:20:00,0.0,2010-04-21 13:20:00
164,40774.0,40774.0,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-05-01,02:10:00,0.0,2010-05-01 02:10:00
185,41573.0,41573.0,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-05-13,16:10:00,0.0,2010-05-13 16:10:00
223,41591.0,41591.0,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-06-10,17:30:00,0.0,2010-06-10 17:30:00
240,41678.0,41678.0,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-06-19,19:05:00,0.0,2010-06-19 19:05:00
242,42011.0,42011.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-06-19,13:16:00,0.0,2010-06-19 13:16:00
248,41729.0,41729.0,ACIDENTE,RIO DE JANEIRO,RJ,NaN,2010-06-25,13:05:00,0.0,2010-06-25 13:05:00
274,41750.0,41750.0,ACIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-07-12,19:53:00,3.0,2010-07-12 19:53:00
284,42067.0,42067.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-07-20,12:41:00,0.0,2010-07-20 12:41:00
296,42634.0,42634.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-07-28,10:05:00,0.0,2010-07-28 10:05:00
298,42436.0,42436.0,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-07-29,19:12:00,0.0,2010-07-29 19:12:00
300,42619.0,42619.0,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-07-30,09:24:00,0.0,2010-07-30 09:24:00
309,42443.0,42443.0,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-08-04,13:27:00,0.0,2010-08-04 13:27:00
319,42284.0,42284.0,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-08-10,12:30:00,0.0,2010-08-10 12:30:00
326,42250.0,42250.0,ACIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-08-12,12:26:00,19.0,2010-08-12 12:26:00
335,42456.0,42456.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-08-21,16:35:00,0.0,2010-08-21 16:35:00
336,42740.0,42740.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-08-21,13:25:00,0.0,2010-08-21 13:25:00
341,42486.0,42486.0,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-08-23,23:55:00,0.0,2010-08-23 23:55:00
352,42603.0,42603.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-08-27,13:27:00,0.0,2010-08-27 13:27:00
359,42598.0,42598.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-08-31,12:35:00,0.0,2010-08-31 12:35:00
375,42714.0,42714.0,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,NaN,2010-09-11,15:30:00,0.0,2010-09-11 15:30:00
377,42868.0,42868.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-09-11,20:30:00,0.0,2010-09-11 20:30:00
386,43064.0,43064.0,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-09-15,17:54:00,0.0,2010-09-15 17:54:00
388,42880.0,42880.0,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,SBJR,2010-09-17,13:55:00,0.0,2010-09-17 13:55:00
389,42882.0,42882.0,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,SBJR,2010-09-17,18:46:00,0.0,2010-09-17 18:46:00
427,43578.0,43578.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-10-04,12:30:00,0.0,2010-10-04 12:30:00
432,43033.0,43033.0,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-10-05,21:46:00,0.0,2010-10-05 21:46:00
456,43699.0,43699.0,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-10-23,17:43:00,0.0,2010-10-23 17:43:00
494,43283.0,43283.0,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-11-20,13:02:00,0.0,2010-11-20 13:02:00
526,43527.0,43527.0,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-12-12,19:00:00,0.0,2010-12-12 19:00:00
527,43462.0,43462.0,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,SBGL,2010-12-13,11:00:00,0.0,2010-12-13 11:00:00
536,43921.0,43921.0,ACIDENTE,RIO DE JANEIRO,RJ,NaN,2010-12-18,13:15:00,0.0,2010-12-18 13:15:00

In [56]:
filtro = dados_2010.ocorrencia_cidade == 'RIO DE JANEIRO'
dados_2010.loc[filtro].total_recomendacoes.sum()

25.0

In [59]:
#Total de recomendações por cidade
filtro = dados_2010.ocorrencia_cidade == 'RIO DE JANEIRO'
filtro2  = dados_2010.total_recomendacoes > 0
dados_2010.loc[filtro & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
119,40190.0,40190.0,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-04-06,02:35:00,3.0,2010-04-06 02:35:00
274,41750.0,41750.0,ACIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-07-12,19:53:00,3.0,2010-07-12 19:53:00
326,42250.0,42250.0,ACIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-08-12,12:26:00,19.0,2010-08-12 12:26:00

In [60]:
dados_2010.groupby(['ocorrencia_cidade']).total_recomendacoes.sum()

ocorrencia_cidade
AMERICANA                 0.0
ARARAQUARA                0.0
ARAÇATUBA                 0.0
AREALVA                   0.0
ARRAIAL DO CABO           0.0
BAURU                     0.0
BEBEDOURO                 0.0
BELO HORIZONTE            2.0
BOCAINA                   0.0
BOITUVA                   1.0
BOM JESUS DO AMPARO       0.0
BOM JESUS DO GALHO        1.0
BRAGANÇA PAULISTA         9.0
BROTAS                    0.0
CAJOBI                    0.0
CAMANDUCAIA               9.0
CAMPINAS                  0.0
CAMPOS DOS GOYTACAZES     0.0
CASIMIRO DE ABREU         0.0
CONFINS                   0.0
COROMANDEL                0.0
COSMÓPOLIS                0.0
DIAMANTINA                0.0
DIVINÓPOLIS               0.0
GUARULHOS                 0.0
IPATINGA                  0.0
IPERÓ                     3.0
ITANHAÉM                  1.0
ITÁPOLIS                  0.0
JUIZ DE FORA              0.0
JUNDIAÍ                   7.0
LINHARES                  0.0
MACAÉ                     0.0
MANGARATIBA               0.0
MARÍLIA                   0.0
MONTES CLAROS             0.0
NOVO HORIZONTE            3.0
OLÍMPIA                   0.0
PARÁ DE MINAS             0.0
PENÁPOLIS                 0.0
PIACATU                   0.0
PIRACICABA                0.0
PIRASSUNUNGA              0.0
POUSO ALEGRE              0.0
POÇOS DE CALDAS           0.0
RESENDE                   8.0
RIBEIRÃO PRETO            0.0
RIO DE JANEIRO           25.0
SANTOS                    0.0
SERRA NEGRA               0.0
SOROCABA                  0.0
SÃO BERNARDO DO CAMPO     2.0
SÃO JOSÉ DO RIO PRETO     0.0
SÃO JOSÉ DOS CAMPOS       0.0
SÃO PAULO                41.0
TIMÓTEO                   3.0
UBERABA                   0.0
UBERLÂNDIA                0.0
VITÓRIA                   0.0
Name: total_recomendacoes, dtype: float64

In [62]:
#Total de recomendações por aerodromo, dropna para aerodromo não informados
dados_2010.groupby(['ocorrencia_aerodromo'], dropna=False).total_recomendacoes.sum()

ocorrencia_aerodromo
SBAE     0.0
SBAQ     0.0
SBBH     0.0
SBBP     9.0
SBBU     0.0
SBCF     0.0
SBGL     3.0
SBGR     0.0
SBIP     0.0
SBJD     7.0
SBJR     3.0
SBKP     0.0
SBME     0.0
SBMK     0.0
SBML     0.0
SBMT    27.0
SBPC     0.0
SBPR     1.0
SBRJ    19.0
SBRP     0.0
SBSJ     0.0
SBSP     0.0
SBSR     0.0
SBUL     0.0
SBUR     0.0
SBVT     0.0
SDAM     0.0
SDOI     1.0
SDPW     0.0
SDPY     0.0
SNDT     0.0
SNDV     0.0
SNXT     0.0
NaN     45.0
Name: total_recomendacoes, dtype: float64

In [64]:
filtro = dados_2010.total_recomendacoes > 0
dados_2010.loc[filtro].groupby(['ocorrencia_cidade']).total_recomendacoes.sum()

ocorrencia_cidade
BELO HORIZONTE            2.0
BOITUVA                   1.0
BOM JESUS DO GALHO        1.0
BRAGANÇA PAULISTA         9.0
CAMANDUCAIA               9.0
IPERÓ                     3.0
ITANHAÉM                  1.0
JUNDIAÍ                   7.0
NOVO HORIZONTE            3.0
RESENDE                   8.0
RIO DE JANEIRO           25.0
SÃO BERNARDO DO CAMPO     2.0
SÃO PAULO                41.0
TIMÓTEO                   3.0
Name: total_recomendacoes, dtype: float64

In [65]:
filtro = dados_2010.total_recomendacoes > 0
dados_2010.loc[filtro].groupby(['ocorrencia_cidade']).total_recomendacoes.sum().sort_values()

ocorrencia_cidade
BOITUVA                   1.0
BOM JESUS DO GALHO        1.0
ITANHAÉM                  1.0
BELO HORIZONTE            2.0
SÃO BERNARDO DO CAMPO     2.0
IPERÓ                     3.0
NOVO HORIZONTE            3.0
TIMÓTEO                   3.0
JUNDIAÍ                   7.0
RESENDE                   8.0
BRAGANÇA PAULISTA         9.0
CAMANDUCAIA               9.0
RIO DE JANEIRO           25.0
SÃO PAULO                41.0
Name: total_recomendacoes, dtype: float64